on:
  push:
    branches:
      - 'main'

env:
  SKAFFOLD_DEFAULT_REPO: registry.209.38.173.206.sslip.io
  

jobs:
  converge:
    name: Skaffold Build
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Log in to registry
        run: echo "${{ secrets.HARBOR_PASSWORD }}" | docker login --username ${{ secrets.HARBOR_USERNAME  }} --password-stdin ${{ env.SKAFFOLD_DEFAULT_REPO }}

      - name: Cache layers
        uses: actions/cache@v3
        with:
          path: "${{ github.workspace }}/.skaffold/cache"
          key: skaffold-${{ hashFiles('**/cache') }}
          restore-keys: |
            skaffold-

      - name: Run echo
        run: |
          echo ${{ env.SKAFFOLD_DEFAULT_REPO }}/$GITHUB_REPOSITORY_OWNER
          echo $GITHUB_REPOSITORY_OWNER


      - name: Run Skaffold pipeline as command
        uses: hiberbee/github-action-skaffold@latest
        id: build
        with:
          command: build --tag $GITHUB_SHA
          repository: ${{ env.SKAFFOLD_DEFAULT_REPO }}/$env:GITHUB_REPOSITORY_OWNER
